/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package View;

import Controller.kelolaStaffController;
import Config.koneksi;
import Model.Session;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aidil
 */
public class AddStaff extends java.awt.Frame {
    
    private Connection conn;

    /**
     * Creates new form AddStaff
     */
    public AddStaff() {
        conn = koneksi.getConnection();
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_username = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        t_password = new javax.swing.JTextField();
        lbl_id = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        lbl_nama = new javax.swing.JLabel();
        t_nama = new javax.swing.JTextField();
        lbl_jabatan = new javax.swing.JLabel();
        lbl_status = new javax.swing.JLabel();
        lbl_JenisKelamin = new javax.swing.JLabel();
        rb_lakiLaki = new javax.swing.JRadioButton();
        rb_perempuan = new javax.swing.JRadioButton();
        btn_tambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        t_status = new javax.swing.JComboBox<>();
        t_jabatan = new javax.swing.JComboBox<>();

        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png")).getImage());
        setLocationRelativeTo(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        lbl_username.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_username.setText("Username");

        t_username.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_username.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lbl_password.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_password.setText("Password");

        t_password.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_passwordActionPerformed(evt);
            }
        });

        lbl_id.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_id.setText("Id");

        t_id.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lbl_nama.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_nama.setText("Nama");

        t_nama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_nama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaActionPerformed(evt);
            }
        });

        lbl_jabatan.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_jabatan.setText("Jabatan");

        lbl_status.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_status.setText("Status");

        lbl_JenisKelamin.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_JenisKelamin.setText("Jenis Kelamin");

        jenisKelamin.add(rb_lakiLaki);
        rb_lakiLaki.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        rb_lakiLaki.setText("Laki-Laki");

        jenisKelamin.add(rb_perempuan);
        rb_perempuan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        rb_perempuan.setText("Perempuan");

        btn_tambah.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("TAMBAH STAFF");

        t_status.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "On", "Off" }));

        t_jabatan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_jabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Kepala Cabang" }));
        t_jabatan.setToolTipText("Pilihan Jabatan");
        t_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_jabatanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_tambah))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_id)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbl_nama)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_JenisKelamin)
                                            .addComponent(lbl_username))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(rb_lakiLaki)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rb_perempuan))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_status)
                                            .addComponent(lbl_jabatan)
                                            .addComponent(lbl_password))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(t_jabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(21, 21, 21))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_JenisKelamin)
                    .addComponent(rb_perempuan)
                    .addComponent(rb_lakiLaki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_username, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_password, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lbl_jabatan)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_status)))
                    .addComponent(t_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btn_tambah)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(568, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Kembali ke frame Login
                menuKP menu = new menuKP();
                menu.setVisible(true);
                dispose(); // Tutup frame Menu
            }
        });
    }//GEN-LAST:event_exitForm

    private void t_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaActionPerformed

    private void t_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_passwordActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        String id = t_id.getText();
        String nama = t_nama.getText();
        String jenisKelamin = rb_lakiLaki.isSelected() ? "Laki-laki" : "Perempuan";
        String username = t_username.getText();
        String password = t_password.getText();
        String jabatan = t_jabatan.getSelectedItem().toString();
        String status = t_status.getSelectedItem().toString();

        // Panggil controller untuk menambahkan data
        kelolaStaffController controller = new kelolaStaffController(conn);
        boolean isAdded = controller.addStaff(id, nama, jenisKelamin, username, password, jabatan, status);

        if (isAdded) {
            // Jika sukses, kembali ke menu utama
            menuKP menu = new menuKP();
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void t_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_jabatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStaff().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jenisKelamin;
    private javax.swing.JLabel lbl_JenisKelamin;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_jabatan;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JRadioButton rb_lakiLaki;
    private javax.swing.JRadioButton rb_perempuan;
    private javax.swing.JTextField t_id;
    private javax.swing.JComboBox<String> t_jabatan;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_password;
    private javax.swing.JComboBox<String> t_status;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables
}
