/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package View;

import Model.Staff;
import Controller.kelolaStaffController;
import Config.koneksi;
import Model.Session;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aidil
 */
public class EditStaff extends java.awt.Frame {
    
    private Connection conn;

    /**
     * Creates new form AddStaff
     */
    public EditStaff() {
        conn = koneksi.getConnection();
        initComponents();
        
        t_id.setText(Staff.userId);
        t_nama.setText(Staff.nama);
        t_jabatan.setText(Staff.jabatan);
        t_status.setText(Staff.status);
        
        if ("Laki-laki".equals(Staff.jenis_kelamin)) {
            rb_lakiLaki.setSelected(true);
        } else if ("Perempuan".equals(Staff.jenis_kelamin)) {
            rb_perempuan.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisKelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lbl_id = new javax.swing.JLabel();
        t_id = new javax.swing.JTextField();
        lbl_nama = new javax.swing.JLabel();
        t_nama = new javax.swing.JTextField();
        lbl_jabatan = new javax.swing.JLabel();
        t_jabatan = new javax.swing.JTextField();
        lbl_status = new javax.swing.JLabel();
        t_status = new javax.swing.JTextField();
        lbl_JenisKelamin = new javax.swing.JLabel();
        rb_lakiLaki = new javax.swing.JRadioButton();
        rb_perempuan = new javax.swing.JRadioButton();
        btn_edit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLocationRelativeTo(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        lbl_id.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_id.setText("Id");

        t_id.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_id.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lbl_nama.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_nama.setText("Nama");

        t_nama.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_nama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_namaActionPerformed(evt);
            }
        });

        lbl_jabatan.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_jabatan.setText("Jabatan");

        t_jabatan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_jabatan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        t_jabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_jabatanActionPerformed(evt);
            }
        });

        lbl_status.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_status.setText("Status");

        t_status.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        t_status.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lbl_JenisKelamin.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lbl_JenisKelamin.setText("Jenis Kelamin");

        jenisKelamin.add(rb_lakiLaki);
        rb_lakiLaki.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        rb_lakiLaki.setText("Laki-Laki");

        jenisKelamin.add(rb_perempuan);
        rb_perempuan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        rb_perempuan.setText("Perempuan");

        btn_edit.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel1.setText("EDIT STAFF");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(btn_edit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_status)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_jabatan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_nama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_id)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_JenisKelamin)
                                .addGap(32, 32, 32)
                                .addComponent(rb_lakiLaki)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_perempuan)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(206, 206, 206))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nama))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_JenisKelamin)
                    .addComponent(rb_perempuan)
                    .addComponent(rb_lakiLaki))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_jabatan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_jabatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_status, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_status))
                .addGap(94, 94, 94)
                .addComponent(btn_edit)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(568, 477));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Kembali ke frame Login
                menuKP menu = new menuKP();
                menu.setVisible(true);
                dispose(); // Tutup frame Menu
            }
        });
    }//GEN-LAST:event_exitForm

    private void t_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_namaActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        String userId = Staff.userId; // ID staff yang sedang diedit
        String nama = t_nama.getText();
        String jenis_kelamin = rb_lakiLaki.isSelected() ? "Laki-laki" : "Perempuan";
        String jabatan = t_jabatan.getText();
        String status = t_status.getText();

        kelolaStaffController controller = new kelolaStaffController(conn);
        boolean success = controller.editStaff(userId, nama, jenis_kelamin, jabatan, status);

        if (success) {
            // Tutup form EditStaff dan kembali ke menu sebelumnya
            this.dispose();
            new menuKP().setVisible(true); // Sesuaikan dengan form utama Anda
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void t_jabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_jabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_jabatanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStaff().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.ButtonGroup jenisKelamin;
    private javax.swing.JLabel lbl_JenisKelamin;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_jabatan;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_status;
    private javax.swing.JRadioButton rb_lakiLaki;
    private javax.swing.JRadioButton rb_perempuan;
    private javax.swing.JTextField t_id;
    private javax.swing.JTextField t_jabatan;
    private javax.swing.JTextField t_nama;
    private javax.swing.JTextField t_status;
    // End of variables declaration//GEN-END:variables
}
